language: c

sudo: enabled
dist: trusty

addons:
    apt:
        packages:
            # 32 bit support
            - gcc-multilib

matrix:
    include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx
     
script:
    - pip install --user https://github.com/intelxed/mbuild/zipball/master
    - python ci.py
    - which python
    - ls /usr/bin/python*
    - ls /opt


